# Generated by Django 4.0.4 on 2022-05-11 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(max_length=128)),
                ('thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('release', models.DateField()),
                ('thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True)),
                ('meter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('celebs', models.ManyToManyField(to='movies.celeb')),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
