# Generated by Django 4.0.4 on 2022-04-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=128)),
                ('thumb', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
